import os
TRENDING_DATA = f'/recommender-storage/models/trending.data'
POPULAR_DATA = f'/recommender-storage/models/popular.data'
GENERIC_DATA = f'/recommender-storage/models/generic.data'
CONTENT_BASED_DATA = f'/recommender-storage/models/content_based.data'
SIMILARITY_MATRIX = f'/recommender-storage/models/similarity.matrix'
PERSONALIZED_SVD_RAW = f'/recommender-storage/models/svd_raw.model'
PERSONALIZED_SVD_DATA = f'/recommender-storage/models/svd_lookup.data'
PERSONALIZED_NCF_MODEL_DIR = f'/recommender-storage/models/ncf'
MOVIE_LENS_MOVIES_DATA = f'/recommender-storage/models/movie_lens_movies.data'
MOVIE_LENS_RATINGS_DATA = f'/recommender-storage/models/movie_lens_ratings.data'
MOVIE_ENCODER = f'/recommender-storage/models/movie.encoder'
MOVIE_DECODER = f'/recommender-storage/models/movie.decoder'
USER_ENCODER = f'/recommender-storage/models/user.encoder'
